### PR TITLE
Fixes token fetching to resolve Error 401

### PR DESCRIPTION
**Pull request by Tarzter**

### CODE REVIEW

**Comment by elekram** [comment]
The response from 'https://oauth2.googleapis.com/token' doesn't return an id_token. It returns an access token. Did you get this working with your changes? I think the 401 error might be from not having your scopes correctly configured at Google's end on the admin console. They need to be passed in to the request and also configured on the admin console.

**Comment by Tarzter** [comment]
Hi, 
Yes I got this working with the changes, the 401 error wasn't due to missconfiguration as when generating the token with the "gcloud auth print-identity-token --impersonate-service-account=\<Service Account\>" command the authentication works.
The fetchToken returned an empty dictionary, I've printed the jsonData (response from google api) and saw that it has only the id_token field, that when returned and used as token - allowed me to successfully authenticate.

**Comment by elekram** [comment]
Right, now I understand, Google are providing different payloads depending on the service.

**Comment by elekram** [comment]
Oaky, created a new release which gets rid of the dictionary and simply returns the response.json() as you did. Also updaed the readme to add your example usage. ✌🏻

**Pull request closed without merging**
